name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          google-chrome --headless --disable-gpu --print-to-pdf=test.pdf --no-pdf-header-footer --virtual-time-budget=5000 'https://stratigraphy.org/chart-data/'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          # Artifact name
          name: pdf # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path:  test.pdf
          # The desired behavior if no files are found using the provided path.
